backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "instagram"
    label: "Instagram Posts"
    folder: "content/instagram"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Caption", name: "caption", widget: "text" }

  - name: "quotes"
    label: "Quotes"
    folder: "content/quotes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Quote", name: "quote", widget: "text" }
      - { label: "Author", name: "author", widget: "string" }
