backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "quotes"
    label: "Quotes"
    folder: "content/quotes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Quote", name: "quote", widget: "text" }
      - { label: "Author", name: "author", widget: "string" }

  - name: "instagram"
    label: "Instagram"
    folder: "content/instagram"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Embed Code", name: "body", widget: "markdown" }
